#! /bin/sh
# /etc/init.d/noip

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system

BASEDIR=/home/pi/Telegramgram2Icecast/audio/
HOST_IP="ip_or_domain"
PASSWORD="password"
MOUNT_POINT="mount_name"

case "$1" in
  start)
    echo "Starting liquidice"
    # run application you want to start
    # exec node /home/pi/tele2ice_ok/t2i.js
    liquidsoap 'output.icecast(%mp3, host='$HOST_IP',port=8000,password='$PASSWORD',mount='$MOUNT_POINT',mksafe(playlist(mode="normal","'$BASEDIR'1.m3u",reload_mode="watch")))'
    ;;
  stop)
    echo "Stopping liquidice"
    # kill application you want to stop
    killall t2i
    ;;
  *)
    echo "Usage: /etc/init.d/liquidice {start|stop}"
    exit 1
    ;;
esac

exit 0

