#! /bin/sh
# /etc/init.d/noip

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system

case "$1" in
  start)
    echo "Starting t2i"
    # run application you want to start
#    exec node /home/pi/tele2ice_ok/t2i.js
     /usr/local/bin/node /home/pi/Telegram2Icecast/t2i.js &
    ;;
  stop)
    echo "Stopping t2i"
    # kill application you want to stop
    killall t2i
    ;;
  *)
    echo "Usage: /etc/init.d/t2i {start|stop}"
    exit 1
    ;;
esac

exit 0
